# These are supported funding model platforms

github: # [YoutacRandS-VA]
patreon: # patreon.com/user?u=107365027
open_collective: #  [Vincent10]
custom: # ['youtacrs.wordpress.com', 'youtacrs8.wordpress.com']
